//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.Domain.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class uiMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal uiMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseTracker.Domain.Resources.Languages.uiMessage", typeof(uiMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD CATEGORY.
        /// </summary>
        public static string ADD_CATEGORY {
            get {
                return ResourceManager.GetString("ADD_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD EXPENSE.
        /// </summary>
        public static string ADD_EXPENSE {
            get {
                return ResourceManager.GetString("ADD_EXPENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD SUB CATEGORY.
        /// </summary>
        public static string ADD_SUB_CATEGORY {
            get {
                return ResourceManager.GetString("ADD_SUB_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is designed as a closed system. All your data is stored only on your device. It is never sent to the internet, shared with third parties, or transferred to any server..
        /// </summary>
        public static string All_data_stored_locally {
            get {
                return ResourceManager.GetString("All_data_stored_locally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔒 Fully Secure and Closed System.
        /// </summary>
        public static string All_safe_and_closed_system {
            get {
                return ResourceManager.GetString("All_safe_and_closed_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMOUNT.
        /// </summary>
        public static string AMOUNT {
            get {
                return ResourceManager.GetString("AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can easily analyze your expenses with charts and summaries based on category, subcategory, and necessity status..
        /// </summary>
        public static string Analyze_expenses_with_charts {
            get {
                return ResourceManager.GetString("Analyze_expenses_with_charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Are_you_sure {
            get {
                return ResourceManager.GetString("Are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES.
        /// </summary>
        public static string CATEGORIES {
            get {
                return ResourceManager.GetString("CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORY.
        /// </summary>
        public static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category already exists..
        /// </summary>
        public static string Category_already_exists {
            get {
                return ResourceManager.GetString("Category_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORY DETAIL.
        /// </summary>
        public static string CATEGORY_DETAIL {
            get {
                return ResourceManager.GetString("CATEGORY_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category is in use. All expenses related to the category will be deleted..
        /// </summary>
        public static string Category_in_use {
            get {
                return ResourceManager.GetString("Category_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application features a clean design with no unnecessary complexity or distracting elements..
        /// </summary>
        public static string Clean_and_distraction_free_design {
            get {
                return ResourceManager.GetString("Clean_and_distraction_free_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📊 Clear and Easy-to-Understand Reporting.
        /// </summary>
        public static string Clear_and_simple_reporting {
            get {
                return ResourceManager.GetString("Clear_and_simple_reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENCY.
        /// </summary>
        public static string CURRENCY {
            get {
                return ResourceManager.GetString("CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOM.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Customizable Experience.
        /// </summary>
        public static string Customizable_experience {
            get {
                return ResourceManager.GetString("Customizable_experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please contact to the system admin..
        /// </summary>
        public static string Error_occurred {
            get {
                return ResourceManager.GetString("Error_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPENSE TRACKER.
        /// </summary>
        public static string EXPENSE_TRACKER {
            get {
                return ResourceManager.GetString("EXPENSE_TRACKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPENSES.
        /// </summary>
        public static string EXPENSES {
            get {
                return ResourceManager.GetString("EXPENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRST DAY of WEEK.
        /// </summary>
        public static string FIRST_DAY_OF_WEEK {
            get {
                return ResourceManager.GetString("FIRST_DAY_OF_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRIDAY.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG EXPENSE!.
        /// </summary>
        public static string LOG_EXPENSE {
            get {
                return ResourceManager.GetString("LOG_EXPENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONDAY.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NECESSARY.
        /// </summary>
        public static string NECESSARY {
            get {
                return ResourceManager.GetString("NECESSARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NECESSARY / UNNECESSARY.
        /// </summary>
        public static string NECESSARY_UNNECESSARY {
            get {
                return ResourceManager.GetString("NECESSARY_UNNECESSARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category can not be deleted..
        /// </summary>
        public static string Other_category_can_not_be_deleted {
            get {
                return ResourceManager.GetString("Other_category_can_not_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application allows you to personalize many settings such as date filters, week start options, category structures, and reporting preferences according to your needs..
        /// </summary>
        public static string Personalize_dates_categories_reports {
            get {
                return ResourceManager.GetString("Personalize_dates_categories_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid amount..
        /// </summary>
        public static string Please_enter_valid_amount {
            get {
                return ResourceManager.GetString("Please_enter_valid_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not use comma..
        /// </summary>
        public static string Please_not_use_comma {
            get {
                return ResourceManager.GetString("Please_not_use_comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a category..
        /// </summary>
        public static string Please_select_category {
            get {
                return ResourceManager.GetString("Please_select_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a sub category..
        /// </summary>
        public static string Please_select_sub_category {
            get {
                return ResourceManager.GetString("Please_select_sub_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFERENCES.
        /// </summary>
        public static string PREFERENCES {
            get {
                return ResourceManager.GetString("PREFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences saved successfully..
        /// </summary>
        public static string Preferences_saved {
            get {
                return ResourceManager.GetString("Preferences_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORTS.
        /// </summary>
        public static string REPORTS {
            get {
                return ResourceManager.GetString("REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATURDAY.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        public static string SELECT {
            get {
                return ResourceManager.GetString("SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 Simple and Fast.
        /// </summary>
        public static string Simple_and_fast {
            get {
                return ResourceManager.GetString("Simple_and_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUB CATEGORY.
        /// </summary>
        public static string SUB_CATEGORY {
            get {
                return ResourceManager.GetString("SUB_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESSFUL.
        /// </summary>
        public static string SUCCESSFUL {
            get {
                return ResourceManager.GetString("SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added..
        /// </summary>
        public static string Successfully_added {
            get {
                return ResourceManager.GetString("Successfully_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated..
        /// </summary>
        public static string Successfully_updated {
            get {
                return ResourceManager.GetString("Successfully_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUNDAY.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS MONTH.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS WEEK.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS YEAR.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THURSDAY.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUESDAY.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNNECESSARY.
        /// </summary>
        public static string UNNECESSARY {
            get {
                return ResourceManager.GetString("UNNECESSARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        public static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SUB CATEGORY.
        /// </summary>
        public static string UPDATE_SUB_CATEGORY {
            get {
                return ResourceManager.GetString("UPDATE_SUB_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEDNESDAY.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📱 Your Data Belongs Only to You.
        /// </summary>
        public static string Your_data_is_yours {
            get {
                return ResourceManager.GetString("Your_data_is_yours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your expenses, categories, and reports are stored entirely locally. The application does not use your personal data anywhere else..
        /// </summary>
        public static string Your_expenses_categories_reports_local {
            get {
                return ResourceManager.GetString("Your_expenses_categories_reports_local", resourceCulture);
            }
        }
    }
}
